export enum actionTypes {
  CRYPTO_PAIRINGS_FETCH = 'CRYPTO/PAIRINGS_FETCH',
  CRYPTO_PAIRINGS_FETCH_SUCCESS = 'CRYPTO/PAIRINGS_FETCH_SUCCESS',
  CRYPTO_PAIRINGS_FETCH_ERROR = 'CRYPTO/PAIRINGS_FETCH_ERROR',
};
